### ISSUE TITLE
Neovim in tmux now fails to receive window-selection keys (Ctrl+h/j/k/l)

### ISSUE THREAD

**Issue by tfiala** [christoomey/vim-tmux-navigator#451]
Something in the changes from May 20th 2025 have broken window navigation within neovim while within tmux.

I'll add more details once I figure them out. Syncing to the latest change before that date (4 or 5 commits) restores the functionality.

**Comment by tfiala** [comment]
The first change where this functionality breaks is this change:
81973db3b7856059d2fa0768d758dd14928bdda0

**Comment by christoomey** [comment]
Hi @tfiala, thanks for reporting. Can you confirm if you're running via TPM or via the instructions from the README, and if from the README, can you confirm the exact vim match regex you're using (just to confirm).

/cc @nfischer as I'd love to have your eyes on this as well. Hoping to keep the fixes you've made, but sounds like we may have broken some things in the process.

**Comment by saaguero** [comment]
@christoomey I'm having the same issue with regular Vim. Doing a quick git bisect show the following commit hash:

64803fdd19a36211eba5e39f86c4cbceae8e1d06

**Comment by PyDataBlog** [comment]
I came here to open the same issue

**Comment by JoeCordingley** [comment]
Same issue in neovim, gnome terminal, tmux 3.4, the issue is present using the instructions in the readme and tpm. I was using tpm and fixed by copying the readme instructions from pre 81973db.

**Comment by veyzz** [comment]
fzf is also broken
using TPM, tmux 3.5a, fzf 0.60.3 (0012183), kitty 0.41.1

**Comment by christoomey** [comment]
Hi folks, sorry for the issues here and thanks for reporting. I've just pushed a fix that should restore the old pattern and hopefully resolve this issue.

Would you mind testing out the latest (https://github.com/christoomey/vim-tmux-navigator/commit/0ecda542c0bd3ea26444044c7f03e469a6bb0bff specfically) to see if it resolves things for you?

**Comment by pepe82sh** [comment]
I've ran into the same issue, updated, and the issue persists. Confirmed I'm on 0ecda54.

**Comment by jrmichell** [comment]
The issue was fixed for me on latest (0ecda542c0bd3ea26444044c7f03e469a6bb0bff).

**Comment by saaguero** [comment]
Issue still present.

So, I'm still using 1cfd6ec which works fine.

tmux: 3.5a
ghostty: 1.1.3
vim: 9.1
MacOS: 15.3.2

**Comment by pepe82sh** [comment]
For completeness:

tmux: 3.4
kitty: 0.42.0
neovim: 0.10.2

**Comment by Emille1723** [comment]
Same issue for me. Tested and got the issue on konsole, wezterm & ghostty. Didn't experience it on rio terminal

**Comment by Ryntak94** [comment]
@christoomey Also still seeing the issue. Glad it's not my config, I'll patiently wait for a fix :)

**Comment by pepe82sh** [comment]
Funnily enough, if I try to go back to an old version, the issue seems not to disappear. I went back as far as d847ea9, which works fine on another machine.

**Comment by pepe82sh** [comment]
I was able to get it to work with neovim 0.11.1. Doesn't explain why old versions didn't work on 0.10.2, but maybe it's a clue.

**Comment by Ryntak94** [comment]
> [@christoomey](https://github.com/christoomey) Also still seeing the issue. Glad it's not my config, I'll patiently wait for a fix :)

Update: I mistakenly only updated in neovim and not in tmux. The issue is now resolved.

**Comment by nfischer** [comment]
Ok, I can repro the issue on my side now (with Chris's fix reverted). I will see if I can reland the regex change without breaking things again.
